services:
    laravel.test:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                WWWGROUP: 1000
        image: sail-8.4/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        volumes:
            - .:/var/www/html
            - /var/www/html/node_modules
        networks:
            - sail
        depends_on:
            - mysql
        restart: always

    nginx:
        image: nginx:stable
        ports:
            - "${APP_PORT:-80}:80"   # expõe para acessar pelo navegador
        volumes:
            - .:/var/www/html
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - laravel.test
        networks:
            - sail
        restart: always

    mysql:
        image: "mysql/mysql-server:8.0"
        ports:
            - "${FORWARD_DB_PORT:-3307}:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: "${DB_DATABASE}"
            MYSQL_USER: "${DB_USERNAME}"
            MYSQL_PASSWORD: "${DB_PASSWORD}"
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: "${MYSQL_EXTRA_OPTIONS}"
        volumes:
            - "sail-mysql:/var/lib/mysql"
            - "./vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - "-p${DB_PASSWORD}"
            retries: 3
            timeout: 5s
        restart: always

networks:
    sail:
        driver: bridge

volumes:
    sail-mysql:
        driver: local
    laravel_storage:
        driver: local
